### PR TITLE
K8s tests restricted part2

### PR DESCRIPTION
**Pull request by AndreyLevchenko**

### CODE REVIEW

**Review by yoavrotems — CHANGES_REQUESTED** [review]
LGTM except some testing functions name

**Comment by AndreyLevchenko** [comment]
@yoavrotems 
I've fixed test names

**Comment by AndreyLevchenko** [comment]
seems I initially incorrectly branched this PR

**Review by yoavrotems — APPROVED** [review]
OK LGTM now great :)

**Pull request merged**
